kind: pipeline
type: docker
name: build-and-test2

trigger:
  branch:
    include:
      - feature/ci-test

steps:
- name: clone2
  image: plugins/git
  settings:
    depth: 50

- name: test2
  image: golang:1.22
  commands:
    - go version
    - echo "Running simple tests"
    - go test -v ./...

- name: notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: test
    template: |
      {{#success build.status}}
        :white_check_mark: Build succeeded! (<{{build.link}}|details>)
      {{else}}
        :x: Build failed! (<{{build.link}}|details>)
      {{/success}}